accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "accounts"

urlpatterns=[
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

ajinmain/urls.py
from django.contrib import admin
from django.urls import path, include
from hello import views

# 127.0.0.1:8000/control/
urlpatterns = [
    path('admin/', admin.site.urls),
    path('control/', include('control.urls')), #path('', include('graph.urls')),
    path('hello/', include('hello.urls')),
    path('accounts/',include('accounts.urls')),
    path('', views.index, name='index'),
]

control/urls.py
from django.urls import path
from . import views
from .views import main

app_name = 'control'

# 127.0.0.1:8000/control/~~~
urlpatterns = [
    path('',main),
    path('ready/',views.control_initialization, name='control_initialization'),
    path('AxmMovePos/', views.AxmMovePos, name='AxmMovePos'),
    path('AxmMoveStartPos/', views.AxmMoveStartPos, name='AxmMoveStartPos'),
    path('AxmMoveStartPos2/', views.AxmMoveStartPos2, name='AxmMoveStartPos2'),
    path('AxmMoveVel/', views.AxmMoveVel, name='AxmMoveVel'),
    path('AxmMoveVel2/', views.AxmMoveVel2, name='AxmMoveVel2'),
    path('HomeSearchMove/', views.HomeSearchMove, name='HomeSearchMove'),
    path('SingleAxisEStop/', views.SingleAxisEStop, name='SingleAxisEStop'),
    path('SingleAxisEStop1/', views.SingleAxisEStop1, name='SingleAxisEStop1'),
    path('SingleAxisEStop2/', views.SingleAxisEStop2, name='SingleAxisEStop2'),
    path('SingleAxisEStop3/', views.SingleAxisEStop3, name='SingleAxisEStop3'),
    path('SingleAxisSStop/', views.SingleAxisSStop, name='SingleAxisSStop'),
    path('SingleAxisSStop1/', views.SingleAxisSStop1, name='SingleAxisSStop1'),
    path('SingleAxisSStop2/', views.SingleAxisSStop2, name='SingleAxisSStop2'),
    path('SingleAxisSStop3/', views.SingleAxisSStop3, name='SingleAxisSStop3'),
    path('AxmMoveEStop/', views.AxmMoveEStop, name='AxmMoveEStop'),
    path('AxmMoveSStop/', views.AxmMoveSStop, name='AxmMoveSStop'),
    path('AxmMoveStartMultiPos/', views.AxmMoveStartMultiPos, name='AxmMoveStartMultiPos'),
    path('AxmMoveStartMultiPos2/', views.AxmMoveStartMultiPos2, name='AxmMoveStartMultiPos2'),
    path('signal_servo_on/', views.signal_servo_on, name='signal_servo_on'),
    path('signal_servo_off/', views.signal_servo_off, name='signal_servo_off'),
    path('SingleAxisStop/', views.SingleAxisStop, name='SingleAxisStop'),
]

hello/urls.py
from django.urls import path, re_path
from . import views

app_name = 'hello'

urlpatterns = [
    path('', views.index, name='index'),
]

hello/models.py
from django.db import models

# Create your models here.

hello/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    # HttpResponse는 요청에 대한 응답을 할때 사용한다
    return render(request, 'hello/hello.html')

templates/hello/hello.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=4, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>controller</title>
        <link rel="icon" href="data:;base64,iVBORw0KGgo=">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/parallax/3.1.0/parallax.min.js"></script>    
        <link rel="stylesheet" type="text/css" href="{% static 'css2/main.css'%}">
    </head>
    <body>
        <!-- about -->
        <div class="about">
            <a class="bg_links social portfolio" href="http://www.ajinextek.com/" target="_blank">
                <span class="icon"></span>
            </a>
            <a class="bg_links social dribbble" href="https://dribbble.com/rafaelalucas" target="_blank">
                <span class="icon"></span>
            </a>
            <a class="bg_links social linkedin" href="https://github.com/DeveloperYun" target="_blank">
                <span class="icon"></span>
            </a>
            <a class="bg_links logo"></a>
        </div>
        <!-- end about -->
        <nav>
            <div class="menu">
                <p class="website_name">
                    AjinExtek
                </p>
            </div>
        </nav>
        <!-- Masthead-->
        
        <section class="wrapper">

            <div class="container">

                <div id="scene" class="scene" data-hover-only="false">


                    <div class="circle" data-depth="1.2"></div>

                    <div class="one" data-depth="0.9">
                        <div class="content">
                            <span class="piece"></span>
                            <span class="piece"></span>
                            <span class="piece"></span>
                        </div>
                    </div>

                    <div class="two" data-depth="0.60">
                        <div class="content">
                            <span class="piece"></span>
                            <span class="piece"></span>
                            <span class="piece"></span>
                        </div>
                    </div>

                    <div class="three" data-depth="0.40">
                        <div class="content">
                            <span class="piece"></span>
                            <span class="piece"></span>
                            <span class="piece"></span>
                        </div>
                    </div>

                    <p class="p404" data-depth="0.50">AjinExtek</p>
                    <p class="p404" data-depth="0.10">AjinExtek</p>

                </div>

                <div class="text">
                    <article>
                        <p>아진엑스텍 웹 컨트롤러 <br>사용가능한 제품군 : MLIII, RTEX, SSCNET</p>
                        {% if user.is_authenticated %}
                            <div class="find-btn">
                                <button class="find-btn1" type="button" onclick="location.href='{% url 'accounts:logout' %}'">
                                    로그아웃
                                </button>
                                <button class="find-btn1" type="button" onclick="location.href='{% url 'control:control_initialization' %}'">
                                    대시보드
                                </button>
                            </div>
                        {%else%}
                        <div class="find-btn">
                            <button class="find-btn1" type="button" onclick="location.href='{% url 'accounts:login' %}'">로그인</button>
                            <button class="find-btn1" type="button" onclick="location.href='{% url 'accounts:signup' %}'">회원가입</button>
                        </div>    
                        {%endif%}
                    </article>
                </div>

            </div>
        </section>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <script>
            // Parallax Code
            var scene = document.getElementById('scene');
            var parallax = new Parallax(scene);
        </script>
    </body>
</html>